"""
schemas.py — 向后兼容 shim，从 schemas/ 包重新导出所有 schema。
实际定义已移至 anchor/extract/schemas/ 目录。
"""

from anchor.extract.schemas import *  # noqa: F401, F403
from anchor.extract.schemas import (
    ExtractedFact,
    ExtractedAssumption,
    ExtractedImplicitCondition,
    ExtractedConclusion,
    ExtractedPrediction,
    ExtractedSolution,
    ExtractedTheory,
    ExtractedRelationship,
    ExtractionResult,
    RawClaim,
    RawEdge,
    Step1Result,
    MergeGroup,
    Step2Result,
    ClassifiedEntity,
    Step3Result,
    ImplicitConditionItem,
    Step4Result,
    PolicyItem,
    PolicyThemeItem,
    Step1PolicyResult,
    PolicyChangeAnnotation,
    PolicyComparisonResult,
    PolicyMeasureSchema,
    PolicySchema,
    PolicyExtractionResult,
    CoreConclusion,
    KeyTheory,
    TopDownAnchorsResult,
    SupportingFact,
    SubConclusion,
    SupportingAssumption,
    SupportingPrediction,
    SupportingSolution,
    SupportingScanResult,
    TypedEntity,
    AbstractedResult,
    MergeDecision,
    MergedResult,
    TypedEdge,
    RelationshipResult,
    ExtractedPlayer,
    ExtractedSupplyNode,
    IndustryContextResult,
    ExtractedIssue,
    ExtractedTechRoute,
    ExtractedMetric,
    IndustryEntitiesResult,
    IndustryEdge,
    IndustryRelationshipResult,
)
